.gitignore
co-log/co-log.cabal
co-log/example/Main.hs
co-log/src/Colog.hs
co-log/src/Colog/Actions.hs

Resolves #5 
This PR contains some boilerplate. Could've been avoided if we had Backpack for `String`, but for now just copy-pasting...

[#5] Add some simple IO actions

---

co-log/co-log.cabal
co-log/example/Main.hs
co-log/src/Colog/Actions.hs
co-log/src/Colog/Message.hs
co-log/src/Colog/Monad.hs
stack.yaml

Resolves #7 
I've added `threadDelay` to see whether it actually works for every message individually.
And currently I'm seeing this output:
```haskell
[Warning] Starting application...
[Warning] Starting application...
[Debug] app: First message...
[Debug] app: First message...
[Info] app: Second message...
[Info] app: Second message...
[2018-09-12 06:24:47.695011 UTC] [ThreadId 11] [Warning] Starting application...
[2018-09-12 06:24:47.695011 UTC] [ThreadId 11] [Warning] Starting application...
[2018-09-12 06:24:49.698865 UTC] [ThreadId 11] [Debug] app: First message...
[2018-09-12 06:24:49.698865 UTC] [ThreadId 11] [Debug] app: First message...
[2018-09-12 06:24:49.699671 UTC] [ThreadId 11] [Info] app: Second message...
[2018-09-12 06:24:49.699671 UTC] [ThreadId 11] [Info] app: Second …
```

[#7] Add ability to print time and thread id

---

co-log/co-log.cabal
co-log/src/Colog/Message.hs

Resolves #8 
```
[Warning] Starting application...
[Warning] Starting application...
[Debug]   app: First message...
[Debug]   app: First message...
[Info]    app: Second message...
[Info]    app: Second message...
[Warning] [09:01:34.379 12 Sep 2018 UTC] [ThreadId 11] Starting application...
[Warning] [09:01:34.379 12 Sep 2018 UTC] [ThreadId 11] Starting application...
[Debug]   [09:01:36.385 12 Sep 2018 UTC] [ThreadId 11] app: First message...
[Debug]   [09:01:36.385 12 Sep 2018 UTC] [ThreadId 11] app: First message...
[Info]    [09:01:36.386 12 Sep 2018 UTC] [ThreadId 11] app: Second message...
[Info]    [09:01:36.386 12 Sep 2018 UTC] [ThreadId 11] app: Second message...
```

[#8] Refactor output

---

co-log/co-log.cabal
co-log/example/Main.hs
co-log/src/Colog/Message.hs
stack.yaml

Resolves #18 
Dayum. I can't believe it's actually working! And I'm so happy to use `typerep-map` :blush: 
```haskell
[Warning] [Main.app#24] Starting application...
[Warning] [Main.app#24] Starting application...
[Debug]   [Main.example#19] app: First message...
[Debug]   [Main.example#19] app: First message...
[Info]    [Main.example#20] app: Second message...
[Info]    [Main.example#20] app: Second message...
[Info]    [Main.app#28] app: Application finished...
[Info]    [Main.app#28] app: Application finished...
[Warning] [11:54:31.809 13 Sep 2018 UTC] [Main.app#24] [ThreadId 7] Starting application...
[Warning] [11:54:31.809 13 Sep 2018 UTC] [Main.app#24] [ThreadId 7] Starting application...
[Debug]   [11:54:32.813 13 Sep 2018 UTC] [Main.example#19] [ThreadId 7] app: First message... …
```

[#18] Implement extensible message format

---

co-log-core/co-log-core.cabal
co-log-core/src/Colog/Core/Action.hs
co-log/co-log.cabal
co-log/src/Colog/Contra.hs

On GHC-8.6.1 and later we export Contravariant instance
directly from the co-log package, as it does not require
additional dependencies.

Export contravariant instance from co-log directly.

---

co-log/co-log.cabal
co-log/src/Colog/Concurrent.hs
co-log/src/Colog/Concurrent/Internal.hs

Introduce two approaches for concurrent log writing
and basic utilities for working with concurrent logs.
Two approaches are needed in order to allow user to
chose between generality and speed, though approaches
were not benchmarked to check the hypothesys.

Introduce basic approach to concurrent log writing.

---

.travis.yml
co-log-core/co-log-core.cabal
co-log/README.md
co-log/co-log.cabal
co-log/src/Colog/Message.hs

[#39] Build with GHC 8.2.2 and GHC 8.6.1 on CI

---

co-log-core/co-log-core.cabal
co-log-core/src/Colog/Core/Action.hs
co-log-core/tests/doctest.hs
co-log/co-log.cabal

Run doctests for co-log-core

---

co-log-core/src/Colog/Core/IO.hs

In the previous merge we added the `liftLogIO` function, but didn't actually export it. It's probably better if we do export it though...

Actually exports the liftLogIO function

---

co-log-core/CHANGELOG.md
co-log-core/src/Colog/Core/Action.hs

Resolves #49 
Adds 2 operator versions of `unLogAction`. I've given both of them a precedence of 5, so that they're higher than the other combinators, so that things like:
```haskell
f >$< log <& msg
```
have to be written as:
```haskell
(f >$< log) <& msg
```
The infixity should also be > 2 to be higher than the monad operators `>>` and `>>=`, so that
we can do things like:
```haskell
msg &> action >> msg &> action
```
Because something like
```haskell
action <& msg <& msg
```
doesn't make sense in terms of the types, I haven't added infixr or infixl.

[#49] Adds and exports (<&) and (&>) comibinators for LogAction

---

stack.yaml

This should resolve #59. I've tested this on my machine (linux, ghc 8.4.3) hopefully the CI agrees.

[#59] Removes unnecessary time extra-dep, fixing stack test

---

.travis.yml
cabal.project
co-log-benchmark/ChangeLog.md
co-log-benchmark/LICENSE
co-log-benchmark/Main.hs
co-log-benchmark/Setup.hs
co-log-benchmark/co-log-benchmark.cabal
stack.yaml

Introduce basic benchmarks of the log mechanism that allows
testing the overhead of the each feature added.
Example output:
```
Dump 10k messages (in a forked process):
baseline                                           0.001114674s
stdout<string                                      0.005194026s
stdout<text                                        0.004967748s
stdout<bytestring                                  0.002918046s
stderr<bytestring                                  0.01753503s
{stdout<>stderr}<bytestring                        0.017461043s
stdout<format<message                              0.009314225s
stdout<format<message{with callstack}              0.009744045s
stdout<format<message{with callstack:5}            0.018102189s
stdout<format<message{with callstack:50} …
```

Introduce basic benchmarks of the library.

---

co-log/src/Colog/Pure.hs

You're not able to use `LoggerT msg (PureLogger msg) a` since it is not possible to use partial applied type synonyms. However, omitting last parameter helps.

Omit last PureLogger parameter

---

co-log-benchmark/Main.hs
co-log-core/CHANGELOG.md
co-log-core/src/Colog/Core/IO.hs
co-log/example/Main.hs

Resovles  #63:
Added the suggested `logPrint` and `logPrintStderr`.
Updated the benchmarks to test `logPrint`.
Updated example to use the new functions.

[#63] Add `logPrint` and `logPrintStderr` to Colog.Core.IO.

---

co-log-core/co-log-core.cabal
co-log-core/src/Colog/Core/Action.hs
co-log/co-log.cabal
co-log/src/Colog/Message.hs
co-log/src/Colog/Monad.hs

Resolves #69.
Uses the standard extensions for kowainik, as mentioned in that issue, and removes unnecessary per file extensions when necessary.

Use standard extensions in co-log

---

.travis.yml
co-log-core/CHANGELOG.md
co-log-core/co-log-core.cabal
co-log-core/src/Colog/Core/Action.hs
co-log-core/src/Colog/Core/IO.hs
co-log-core/test/Doctests.hs
co-log/CHANGELOG.md
co-log/co-log.cabal
stack.yaml

Resolves #13 
I've updated `.cabal` description. Haven't checked it yet, just took `vec` package as an example:
* https://github.com/phadej/vec/blob/6eaa4f5ee258a709cab2342233f4539e73fd393a/vec/vec.cabal#L8-L60
Also I've update GHC versions in `.cabal` file and on Travis CI. And performed a couple more documentation improvements.

[#13] Improve documentation and description

---

co-log-core/README.md
co-log-core/src/Colog/Core/Action.hs
co-log/co-log.cabal

Adds stackage badges to `co-log-core` package due to this PR:
* https://github.com/commercialhaskell/stackage/pull/4135
Also couple extra fixes.

Add badges and fix docs

---

co-log/co-log.cabal
co-log/src/Colog/Message.hs
co-log/tutorials/Main.hs

Resolves #119 
- I refactored a bit trying to avoid duplicate code as per hlint suggestions
- I ran play-colog and I can in fact see the logs without the severity information

[#119] new action that logs a message without the severity information

---

co-log/src/Colog/Rotation.hs

This commit fixes the basic behavior of log rotation.
tested with below config, log files are cleaned if there is more than 5 files...
```haskell
withLogRotation (LimitTo 200) (LimitTo 5) "test.log" D.removeFile (
```

[#133] make rotation works

---

.gitignore
co-log-polysemy/co-log-polysemy.cabal
stack.yaml

Now, `co-log-polysemy` should build with the latest 3 major versions of GHC.

Bump up polysemy

---

co-log-polysemy/co-log-polysemy.cabal
co-log-polysemy/src/Colog/Polysemy/Effect.hs
stack.yaml

I am opening this PR before `0.8` is released, it is not meant to be merged yet.
If you want to use co-log with polysemy master see the [polysemy-0.8-submodules branch](https://github.com/Avi-D-coder/co-log/tree/polysemy-0.8-submodules).

Update polysemy ^>= 1.0

---

README.md
co-log/co-log.cabal
co-log/tutorials/Concurrent.hs

Resolves #124
I tested it locally, I don't see any interleaved output. I see the following correct output:
```
Logging from thread: 4
Logging from thread: 5
Logging from thread: 3
Logging from thread: 6
Logging from thread: 1
Logging from thread: 2
Logging from thread: 10
Logging from thread: 8
Logging from thread: 4
Logging from thread: 6
Logging from thread: 7
Logging from thread: 2
Logging from thread: 10
Logging from thread: 8
Logging from thread: 4
Logging from thread: 9
Logging from thread: 6
Logging from thread: 2
Logging from thread: 10
```
So if somebody has problems with concurrent logging, we at least have a place to experiment with such problems...

[#124] Implement concurrent playground for logging

---

co-log-core/CHANGELOG.md
co-log-core/src/Colog/Core/Action.hs

Resolves #139
instances for `Applicative` and `Monad` cannot be created as they imply `Functor` instance which immediately gives introduced here custom type error.

[#139] Add type-errors for `LogAction` instances

---

co-log/src/Colog/Message.hs

This addresses #191.
Resolves #191
The `showTime` function is useful on it‘s own, especially for other logging solutions.

Export showTime

---

co-log-core/src/Colog/Core/IO.hs
co-log/src/Colog/Actions.hs

I find it quite disappointing that actions provided out of the box do not flush output buffers. I have found a couple of relevant issues: #176 and #184. AFAIU it was supposed to be resolved already, but apparently it's not, so I went ahead and opened this PR.
For now I only add `logFlush` action which I believe is useful on its own as a basic building block for other actions. For example, if you want to log to `stderr`, you can construct the following action: `logPrintStderr <> logFlush stderr`. This PR is WIP because we should decide what to do further.
I propose to update all actions that write to a handle (be it a file or a standard handle) to flush by default. That's in line with this comment: https://github.com/kowainik/co-log/issues/176#issuecomment-578730791
Then the only question …

[#176] Add an action to flush a handle

---

co-log/src/Colog/Monad.hs

I browsed the co-log documentation at http://hackage.haskell.org/package/co-log-0.4.0.1/docs/Colog-Monad.html and wondered where HasLog is coming from or what it was. This PR exposes HasLog from Colog.Monad hopefully simplifying import lists and reducing confusion.
(Also, great talk on Stan over at haskell.love)

Export HasLog from Colog.Monad

---

.github/workflows/ci.yml
co-log-benchmark/co-log-benchmark.cabal
co-log-core/CHANGELOG.md
co-log-core/co-log-core.cabal
co-log-polysemy/CHANGELOG.md
co-log-polysemy/co-log-polysemy.cabal
co-log/CHANGELOG.md
co-log/co-log.cabal

Relaxes `base` bounds, bumps `typerep-map` and `polysemy`.

GHC 9 support

---

.github/workflows/ci.yml
co-log/co-log.cabal
co-log/src/Colog/Message.hs
stack.yaml

Arises from https://github.com/co-log/co-log/issues/217. As a first commit, just the basic changes to reduce code duplication.

Support custom formatting - especially allow easy TZ support 😄 

---

src/Colog/Actions.hs

Problem:
Function to print text with newline which is in use in library performs
it as two separate actions - first is to print message and second - to
print newline symbol.
This way there is issues with computations in multiple threads, so
newline symbol sometimes printed in wrong place.
Solution:
Redefine logger action to use version where newline symbol appended
before printing.

Fix logs printing in multiple threads

---

cabal.project

The referenced repository no longer exists - build failed.

Fix for CI build.

---

.github/workflows/ci.yml
co-log.cabal
src/Colog/Message.hs
tutorials/Main.hs

I'd love to be able to compile a project of mine (which has co-log as dependency) with GHC 9.2.4.
Could you please accept this PR bumping base version bound for that purpose?
I also extended CI config and fixed 2 warnings issues by the new version of ghc..

Allow building with GHC 9.2

---

README.md

I change the tutorial link to a relative path to benefit local reading so it will jump inside the viewer instead of opening a new web page.

docs: use relative path to benefit locally reading

---

README.md
tutorials/README.md

- aggregated all the tutorial pages together and put a link to the tutorial readme.
- format the markdown using the `Prettier` plugin.
- fix: previously, the second link with the title *Using custom monad that stores LogAction inside its environment* is wrong and caused a 404. I apologize for such a careless mistake and fixed it in this PR.
Regards

docs: add a link to tutorial pages and aggregate all tutorial pages

---

.github/workflows/publish.yaml

Edit think it might be a good idea to test this when releasing v0.6 (will provide another PR for release preparation when time has come).
Reminder for myself: Add my hackage token to org secrets before!

Create tags and upload package candidates on version bumps.

---

co-log.cabal
src/Colog/Message.hs

Would be a breaking change, but simplifies code and reduces dependencies (and therefore closes #190).
But we would get slower - around factor 3 - is this acceptable?
(also take into account that these are the times for 10k messages)

Move away from `chronos`.
