- .travis.yml
- cabal.project
- co-log-core/src/Colog/Core/Action.hs
- co-log/CHANGELOG.md
- co-log/LICENSE
- co-log/co-log.cabal
- co-log/src/Colog.hs
- co-log/src/Colog/Name.hs
- co-log/src/Prelude.hs
- stack.yaml
First simple and small changes to bring `co-log` package which depends on `co-log-core`.
> Add Name module to co-log package

- .travis.yml
- co-log-core/co-log-core.cabal
- co-log-core/src/Colog/Core.hs
- co-log-core/src/Colog/Core/Action.hs
- co-log-core/src/Colog/Core/Class.hs
- co-log/co-log.cabal
- co-log/example/Main.hs
- co-log/src/Colog.hs
- co-log/src/Colog/Monad.hs
- stack.yaml
This PR implements general idea of interface for `co-log` and some useful combinators.
> Implement co-log interface

- co-log-core/co-log-core.cabal
- co-log-core/src/Colog/Core.hs
- co-log-core/src/Colog/Core/Severity.hs
- co-log/co-log.cabal
- co-log/example/Main.hs
- co-log/src/Colog.hs
- co-log/src/Colog/Message.hs
> [#6] Add severity and LogMessage with severity

- co-log-core/src/Colog/Core/Action.hs
- co-log/co-log.cabal
- co-log/src/Colog.hs
- co-log/src/Colog/Contra.hs
- stack.yaml
> [#9] Add Contravariant, Divisible, Decidable instances

- co-log-core/src/Colog/Core/Action.hs
> [#17] Add contravariant operators

- co-log/example/Main.hs
Resolves #27 
Maybe not the best example. But at least shows how to use combinators.
```
Logging make...
Toyota
Finished logging make...
Logging model..
Corolla
Finished logging model...
Logging pistons...
4
```
> [#27] Add contravariant example

- co-log/co-log.cabal
- co-log/example/Main.hs
- co-log/src/Colog.hs
- co-log/src/Colog/Monad.hs
- co-log/src/Colog/Pure.hs
Resolves #21 
Maybe we don't have all fancy features yet. But we can add them later after writing tutorial for pure logging.
> [#21] Add pure logging

- README.md
- co-log-core/README.md
- co-log/README.lhs
- co-log/README.md
- co-log/co-log.cabal
Resolves #32 
@vrom911 Please, read and tell what else would be good to add :slightly_smiling_face: We will have several few tutorials. But since API can be changed, let's have only one tutorial for now. You wrote a lot of tutorials on logging libraries, so, please, let me know, what would be good to add to this tutorial :pray:
> [#32] Add readme with example

- co-log/example/Main.hs
- co-log/src/Colog/Message.hs
> [#19] Add logException

- co-log-core/CHANGELOG.md
- co-log-core/co-log-core.cabal
- co-log/CHANGELOG.md
- co-log/co-log.cabal
- co-log/example/Main.hs
- stack.yaml
> [#37] Add bounds to all deps

- co-log-core/CHANGELOG.md
- co-log-core/co-log-core.cabal
- co-log-core/src/Colog/Core/Action.hs
- co-log/co-log.cabal
- co-log/example/Main.hs
> Rename cbind to cmapM - #38

- co-log-core/CHANGELOG.md
- co-log-core/co-log-core.cabal
- co-log-core/src/Colog/Core.hs
- co-log-core/src/Colog/Core/IO.hs
- co-log/CHANGELOG.md
- co-log/co-log.cabal
- co-log/src/Colog/Actions.hs
> [#46] Move log actions that work with String to Colog.Core.IO

- co-log-core/CHANGELOG.md
- co-log-core/src/Colog/Core/IO.hs
Resolves #48.
Hopefully this is a much cleaner pull than the other thread we had.  :)
> [#48] adds liftLogIO

- co-log/co-log.cabal
- co-log/src/Colog.hs
- co-log/src/Colog/Actions.hs
- co-log/src/Colog/Message.hs
- co-log/src/Colog/Monad.hs
- co-log/src/Colog/Rotation.hs
(will) Resolve #20 
I'm currently trying to solve the compilation error, I guess I should combine `putStrLn` somewhere but the type tetris is failing me. I opened the PR anyway to check if you like the approach or if you have any other remark, please do tell.
> [#20] Add logger rotation action

- co-log/co-log.cabal
- co-log/example/Main.hs
Example of using `LogAction` from custom monad.
> Add example of using co-log with custom monad

- co-log/co-log.cabal
- co-log/test/Property.hs
I'd like to commit tests I've written since I won't have ability to continue for a while.
> Added some property tests

- co-log/example/Main.hs
> Add example of using pipe operator (<&)

- co-log-core/CHANGELOG.md
- co-log-core/src/Colog/Core/Class.hs
Resolves #85 
I'm not 100% certain that I did what you meant with:
> And add default implementation to setLogAction function.
> Added overLogAction to HasLog typeclass

- co-log-core/src/Colog/Core/Action.hs
> [#89]  Add cmapMaybe function

- .travis.yml
- README.md
- cabal.project
- co-log-benchmark/Main.hs
- co-log-benchmark/co-log-benchmark.cabal
- co-log-core/co-log-core.cabal
- co-log/co-log.cabal
- stack.yaml
I've also simplified `.travis.yml` according to our new approach.
> Refactor benchmarks and insert results to README

- co-log-benchmark/Main.hs
- co-log-core/co-log-core.cabal
- co-log/CHANGELOG.md
- co-log/co-log.cabal
- co-log/example/Main.hs
- co-log/src/Colog.hs
- co-log/src/Colog/Actions.hs
- co-log/src/Colog/Concurrent.hs
- co-log/src/Colog/Concurrent/Internal.hs
- co-log/src/Colog/Contra.hs
- co-log/src/Colog/Message.hs
- co-log/src/Colog/Monad.hs
- co-log/src/Colog/Pure.hs
- co-log/src/Colog/Rotation.hs
> [#103] Make Message polymorphic, improve docs

- co-log-core/CHANGELOG.md
- co-log-core/src/Colog/Core.hs
- co-log-core/src/Colog/Core/Action.hs
- co-log-core/src/Colog/Core/Class.hs
- co-log-core/src/Colog/Core/IO.hs
- co-log-core/src/Colog/Core/Severity.hs
> [#101] Add logActionL lens, impove docs a bit

- co-log-core/CHANGELOG.md
- co-log-core/co-log-core.cabal
- co-log-core/src/Colog/Core/Action.hs
- co-log-core/test/Doctests.hs
> [#99] Add more comonadic combinators

- co-log-core/src/Colog/Core/Action.hs
- co-log-core/src/Colog/Core/IO.hs
- co-log-core/src/Colog/Core/Severity.hs
- co-log/src/Colog/Actions.hs
- co-log/src/Colog/Message.hs
- co-log/src/Colog/Monad.hs
- co-log/src/Colog/Pure.hs
> [#110] Add SPECIALIZE and INLINE pragmas

- co-log/CHANGELOG.md
- co-log/src/Colog/Actions.hs
> [#96] Impl Message logging actions

- README.md
- co-log-benchmark/Main.hs
Resolves #95
@chshersh could you please run it on your machine to check the results.
> [#95] Improve bench

- co-log/co-log.cabal
> [#126] Bump up hedgehog to 1.0

- co-log-core/src/Colog/Core/Class.hs
Implements #123 
Signed-off-by: Sanchayan Maity <maitysanchayan@gmail.com>
> Write default implementation to getLogAction via logActionL

- co-log-core/src/Colog/Core/Action.hs
Resolves #138.
Haven't figured out a nice example/test for it. :/
Also, I had to add the `Rank2Types` language extension.
> [#138] Add higher-order transformation function

- co-log-core/src/Colog/Core/Action.hs
r/t https://github.com/kowainik/co-log/issues/125
> Issue 125 - monadic version of functions

- .travis.yml
- co-log-benchmark/co-log-benchmark.cabal
- co-log-core/co-log-core.cabal
- co-log-polysemy/co-log-polysemy.cabal
- co-log/co-log.cabal
- stack.yaml
> [#148] Support GHC-8.8.1

- README.md
- appveyor.yml
- co-log-benchmark/co-log-benchmark.cabal
- co-log/CHANGELOG.md
- co-log/co-log.cabal
- stack.yaml
> [#144] Add Windows CI (AppVeyor)

- co-log-polysemy/CHANGELOG.md
- co-log-polysemy/co-log-polysemy.cabal
- co-log-polysemy/src/Colog/Polysemy/Effect.hs
> [#121] Deeper integration with polysemy

- co-log/CHANGELOG.md
- co-log/src/Colog.hs
- co-log/src/Colog/Concurrent.hs
- co-log/src/Colog/Concurrent/Internal.hs
- co-log/src/Colog/Monad.hs
Resolves #156
I'm not sure how to make this documentation compilable via `doctest`, need to think more about that... But I copy-pasted example of `withBackgroundLogger` to a separate file and made it compile.
> [#156] Fix docs for 'Colog.Concurrent'

- co-log-core/CHANGELOG.md
- co-log-core/co-log-core.cabal
- co-log-core/src/Colog/Core/Action.hs
- co-log-core/src/Colog/Core/IO.hs
- co-log-core/test/Doctests.hs
> [#122] Add separate combinator

- README.md
> [#162] Write more beginner-friendly README

- .stylish-haskell.yaml
- .travis.yml
- co-log-core/CHANGELOG.md
- co-log-core/co-log-core.cabal
- co-log-core/src/Colog/Core/Action.hs
- co-log-core/src/Colog/Core/Class.hs
- co-log-core/src/Colog/Core/IO.hs
- co-log-core/src/Colog/Core/Severity.hs
- co-log-core/test/Doctests.hs
- co-log-polysemy/CHANGELOG.md
- co-log-polysemy/co-log-polysemy.cabal
- co-log/CHANGELOG.md
- co-log/co-log.cabal
- co-log/src/Colog/Concurrent.hs
- co-log/src/Colog/Message.hs
- co-log/src/Colog/Monad.hs
- co-log/src/Colog/Pure.hs
- co-log/src/Colog/Rotation.hs
- co-log/test/Property.hs
- co-log/tutorials/2-custom/Custom.md
- co-log/tutorials/Main.hs
- stack.yaml
This PR includes:
* Update CHANGELOG before release
* Add `@since` annotations
* Add `-Wmissing-deriving-strategies`
* Improve documentation cover
* Add missing functions for `SimpleMsg`
* Build with GHC-8.8.2
* Update Travis CI jobs
* Some minor code refactoring
> Clean up before release

- co-log/CHANGELOG.md
- co-log/src/Colog/Message.hs
> [#155] Introduce beginner-friendly alias for 'cmap'

- co-log-polysemy/CHANGELOG.md
- co-log-polysemy/co-log-polysemy.cabal
> [#181] Bump up 'polysemy' in 'co-log-polysemy' to 1.3.0.0

- co-log-core/co-log-core.cabal
> [#195] Allow doctest-0.17

- co-log/src/Colog/Message.hs
> [#197] Remove strict annotation of msgText

- .github/workflows/ci.yml
- README.md
- co-log/README.md
> [#211] Update the default branch to main

- co-log/co-log.cabal
Builds and passes test.
Closes #200.
> Allow ansi-terminal 0.11

- .github/workflows/ci.yml
- co-log.cabal
Don't want to cause a hurry; just a reminder to support ghc 9.4 (#251) ❤️
> Support GHC 9.4.

- .github/CODEOWNERS
Added myself as a codeowner in order to be allowed to do reviews/merges.
> Added @alaendle as code owner.
